### ISSUE TITLE
[Linux] Segfault when specific Controller Profile is set in a Game Profile

### ISSUE THREAD

**Issue by jn64** [cemu-project/Cemu#392]
Cemu version: 9ebbfb3
OS: Fedora 36
GPU: NVIDIA GeForce GTX 1050 Ti
Driver version: 520.56.06
Game: Breath of the Wild (EU, v208 / 1.5.0), Bayonetta 2 (EU)

## Description

Cemu segfaults if a specific Controller Profile is set in a game's Game Profile.

- For BotW, it segfaults after the the "loading cached Vulkan pipelines" screen; for Bayonetta 2 it segfaults almost immediately
- Controller is standard Xbox 360 Wired, using SDLController

## Steps to reproduce

1. Delete `controllerProfiles/*`
2. Start Cemu, add a Controller Profile in Input settings
3. Launch game successfully
4. Restart Cemu, edit game's Game Profile and select that Controller Profile for Controller 1
5. Launch game, segfault

## Logs

Cemu log
[log.txt](https://github.com/cemu-project/Cemu/files/9875963/log.txt)

Controller profile: [X360.xml.zip](https://github.com/cemu-project/Cemu/files/9817659/X360.xml.zip)

Backtrace (truncated because it goes on *forever*):
```
#0  0x0000000000b56468 in SDL_GameControllerGetButton_REAL ()
#1  0x0000000000a5aed8 in SDLController::raw_state() ()
#2  0x0000000000a4a215 in ControllerBase::update_state() ()
#3  0x0000000000a61798 in VPADController::VPADRead(VPADStatus&, BtnRepeat const&) ()
#4  0x00000000007e06cd in vpad::VPADRead(int, VPADStatus*, unsigned int, betype<int>*) ()
#5  0x00000000007e354f in void cafeExportCallWrapper<&vpad::VPADRead, vpad::load()::StringWrapper, (LogType)6>(PPCInterpreter_t*) [clone .llvm.1965343467874212314] ()
#6  0x00000000006fa4d8 in coreinit::__OSFiberThreadEntry(void*) ()
#7  0x00007ffff7aab7c0 in __start_context () at ../sysdeps/unix/sysv/linux/x86_64/__start_context.S:90
#8  0x00007ffea118d720 in  ()
#9  0x0402000086639d02 in  ()
#10 0x26649d0284201b00 in  ()
#11 0x000000000000d815 in  ()
#12 0x00007ffea0000860 in  ()
#13 0x00007ffea0000860 in  ()
#14 0x00007ffea1559460 in  ()
#15 0x00007ffea1559460 in  ()
#16 0x2e669d0204131800 in  ()
#17 0x1039260004020000 in  ()
#18 0x0402000036669d02 in  ()
#19 0x4e669d0204131800 in  ()
#20 0x1413180006020000 in  ()
#21 0x040200005a669d02 in  ()
#22 0x6a669d0214131800 in  ()
#23 0xe412180006020000 in  ()
#24 0x0402000076669d02 in  ()
#25 0x8a669d02e4121800 in  ()
#26 0x2413180006020000 in  ()
#27 0x0402000096669d02 in  ()
#28 0xaa669d0224131800 in  ()
#29 0xf412180006020000 in  ()
#30 0x04020000b6669d02 in  ()
#31 0xca669d02f4121800 in  ()
#32 0x3413180006020000 in  ()
#33 0x04020000d6669d02 in  ()
#34 0x02679d0234131800 in  ()
#35 0x4013180006020000 in  ()
#36 0x040200000a679d02 in  ()
#37 0x0e679d0240131800 in  ()
#38 0x4413180006020000 in  ()
#39 0x0402000016679d02 in  ()
#40 0x1a679d0244131800 in  ()
#41 0xfc9d4f0006020000 in  ()
#42 0x040200001e679d02 in  ()
#43 0x22679d02fc9d4f00 in  ()
#44 0xf49d4f0006020000 in  ()
#45 0x040200002a679d02 in  ()
#46 0x2e679d02f49d4f00 in  ()
#47 0xf09d4f0006020000 in  ()
...
```

**Comment by jn64** [comment]
Fixed by 3df8217a0220956a3308faa8229d6c4d74bb21de. Last commit with the crash is ec6726e85c102c5f02ebc0c99f1d91659c81a882
