### ISSUE TITLE
GUI, Linux: crash when browsing folders with valid files that have a preview image

### ISSUE THREAD

**Issue by Tatsh** [cemu-project/Cemu#53]
```
(Cemu2:16404): Gtk-CRITICAL **: 06:32:37.951: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
SIGSEGV!
Error: signal 11:
./src/Cemu2(+0x682209)[0x55ee2e114209]
/lib64/libc.so.6(+0x3dde0)[0x7f50b92e6de0]
/usr/lib64/libpng16.so.16(+0xd376)[0x7f50bac73376]
/usr/lib64/libpng16.so.16(+0x1df09)[0x7f50bac83f09]
/usr/lib64/libpng16.so.16(+0x21eeb)[0x7f50bac87eeb]
/usr/lib64/libpng16.so.16(+0xe5f6)[0x7f50bac745f6]
/usr/lib64/libpng16.so.16(png_process_data+0x3b)[0x7f50bac7517b]
/usr/lib64/libgdk_pixbuf-2.0.so.0(+0x1dd29)[0x7f50b9dd2d29]
/usr/lib64/libgdk_pixbuf-2.0.so.0(+0x1210b)[0x7f50b9dc710b]
/usr/lib64/libgdk_pixbuf-2.0.so.0(gdk_pixbuf_loader_write+0x21e)[0x7f50b9dc7c8e]
/usr/lib64/libgdk_pixbuf-2.0.so.0(gdk_pixbuf_new_from_file_at_scale+0x136)[0x7f50b9dc4d16]
/usr/lib64/libgtk-3.so.0(+0x1ec017)[0x7f50ba5ec017]
/usr/lib64/libgtk-3.so.0(+0x1e1081)[0x7f50ba5e1081]
/usr/lib64/libgtk-3.so.0(+0x1eedc8)[0x7f50ba5eedc8]
/usr/lib64/libgtk-3.so.0(+0x1eee9d)[0x7f50ba5eee9d]
/usr/lib64/libgtk-3.so.0(+0x143e70)[0x7f50ba543e70]
/usr/lib64/libglib-2.0.so.0(g_hash_table_foreach+0x60)[0x7f50ba171a30]
/usr/lib64/libgtk-3.so.0(+0x143d49)[0x7f50ba543d49]
/usr/lib64/libgtk-3.so.0(+0x1495bb)[0x7f50ba5495bb]
/usr/lib64/libgtk-3.so.0(+0x3fb1b7)[0x7f50ba7fb1b7]
/usr/lib64/libgobject-2.0.so.0(+0x16862)[0x7f50ba0e6862]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit_valist+0xf73)[0x7f50ba0fef53]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit+0x97)[0x7f50ba0ff157]
/usr/lib64/libgtk-3.so.0(gtk_cell_area_apply_attributes+0xb6)[0x7f50ba545a86]
/usr/lib64/libgtk-3.so.0(+0x37bf17)[0x7f50ba77bf17]
/usr/lib64/libgtk-3.so.0(+0x37f107)[0x7f50ba77f107]
/usr/lib64/libgtk-3.so.0(+0x385675)[0x7f50ba785675]
/usr/lib64/libgdk-3.so.0(+0x2ec89)[0x7f50bacedc89]
/usr/lib64/libglib-2.0.so.0(g_main_context_dispatch+0x175)[0x7f50ba1839d5]
/usr/lib64/libglib-2.0.so.0(+0x54d78)[0x7f50ba183d78]
/usr/lib64/libglib-2.0.so.0(g_main_loop_run+0x73)[0x7f50ba184063]
/usr/lib64/libgtk-3.so.0(gtk_main+0x6d)[0x7f50ba64ef4d]
terminate called without an active exception
Aborted (core dumped)
```

In the Gtk+ open file dialog, as soon as I click to browse the folder with a WUX file, the app immediately crashes with the above.

I checked other Gtk+ apps like Audacity. Previews show fine in the open file dialog and the apps do not crash. This only happens in Cemu.

Just to make sure, I removed [ROM Properties](https://github.com/GerbilSoft/rom-properties) from my machine while testing.

**Comment by Tatsh** [comment]
I think this issue may be that the thumbnail in question was malformed? I deleted the mentioned file below and even with ROM Properties installed I don't see a preview in the Open File dialog (like in Audacity) but the crash does not occur.

Full stack trace:

```
#0  png_malloc_base (png_ptr=0x5555581629c0, size=61) at /var/tmp/portage/media-libs/libpng-1.6.37-r2/work/libpng-1.6.37/pngmem.c:91
#1  0x00007ffff70e8f09 in png_read_buffer (warn=2, new_size=61, png_ptr=0x5555581629c0) at /var/tmp/portage/media-libs/libpng-1.6.37-r2/work/libpng-1.6.37/pngrutil.c:313
#2  png_read_buffer (png_ptr=0x5555581629c0, new_size=61, warn=2) at /var/tmp/portage/media-libs/libpng-1.6.37-r2/work/libpng-1.6.37/pngrutil.c:298
#3  0x00007ffff70eceeb in png_handle_zTXt (png_ptr=0x5555581629c0, info_ptr=0x55555822c680, length=61) at /var/tmp/portage/media-libs/libpng-1.6.37-r2/work/libpng-1.6.37/pngrutil.c:2636
#4  0x00007ffff70d95f6 in png_push_read_chunk (png_ptr=0x5555581629c0, info_ptr=0x55555822c680) at /var/tmp/portage/media-libs/libpng-1.6.37-r2/work/libpng-1.6.37/pngpread.c:484
#5  0x00007ffff70da13d in png_process_some_data (png_ptr=<optimized out>, info_ptr=<optimized out>) at /var/tmp/portage/media-libs/libpng-1.6.37-r2/work/libpng-1.6.37/pngpread.c:109
#6  0x00007ffff70da17b in png_process_data (png_ptr=0x5555581629c0, info_ptr=0x55555822c680, buffer=buffer@entry=0x55555821d00c "\211PNG\r\n\032\n", buffer_size=buffer_size@entry=4096)
    at /var/tmp/portage/media-libs/libpng-1.6.37-r2/work/libpng-1.6.37/pngpread.c:46
#7  0x00007ffff6bf3d29 in gdk_pixbuf__png_image_load_increment (context=0x5555581103b0, buf=0x55555821d00c "\211PNG\r\n\032\n", size=4096, error=<optimized out>) at ../gdk-pixbuf-2.42.9/gdk-pixbuf/io-png.c:596
#8  0x00007ffff6be810b in gdk_pixbuf_loader_load_module (loader=loader@entry=0x55555792f4c0 [GdkPixbufLoader], image_type=image_type@entry=0x0, error=error@entry=0x0)
    at ../gdk-pixbuf-2.42.9/gdk-pixbuf/gdk-pixbuf-loader.c:477
#9  0x00007ffff6be8c8e in gdk_pixbuf_loader_eat_header_write (error=0x0, count=65536, buf=0x7ffffffea9f0 "\211PNG\r\n\032\n", loader=0x55555792f4c0 [GdkPixbufLoader])
    at ../gdk-pixbuf-2.42.9/gdk-pixbuf/gdk-pixbuf-loader.c:499
#10 gdk_pixbuf_loader_write (loader=loader@entry=0x55555792f4c0 [GdkPixbufLoader], buf=buf@entry=0x7ffffffea9f0 "\211PNG\r\n\032\n", count=65536, error=error@entry=0x0)
    at ../gdk-pixbuf-2.42.9/gdk-pixbuf/gdk-pixbuf-loader.c:540
#11 0x00007ffff6be5d16 in gdk_pixbuf_new_from_file_at_scale
    (filename=filename@entry=0x5555581f1130 "/home/tatsh/.cache/thumbnails/large/ba1a0f361a1aed9915d913983e8cb8bd.png", width=width@entry=16, height=height@entry=16, preserve_aspect_ratio=preserve_aspect_ratio@
entry=1, error=error@entry=0x0) at ../gdk-pixbuf-2.42.9/gdk-pixbuf/gdk-pixbuf-io.c:1422
#12 0x00007ffff6be5f1d in gdk_pixbuf_new_from_file_at_size
    (filename=filename@entry=0x5555581f1130 "/home/tatsh/.cache/thumbnails/large/ba1a0f361a1aed9915d913983e8cb8bd.png", width=width@entry=16, height=height@entry=16, error=error@entry=0x0)
    at ../gdk-pixbuf-2.42.9/gdk-pixbuf/gdk-pixbuf-io.c:1247
#13 0x00007ffff73ec017 in _gtk_file_info_render_icon_internal (symbolic=0, icon_size=16, widget=0x555557ed2c40 [GtkFileChooserWidget], info=0x555558121c70 [GFileInfo])
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkfilesystem.c:836
#14 _gtk_file_info_render_icon (info=info@entry=0x555558121c70 [GFileInfo], widget=widget@entry=0x555557ed2c40 [GtkFileChooserWidget], icon_size=16)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkfilesystem.c:878
#15 0x00007ffff73e1081 in file_system_model_set (model=0x555558054550 [GtkFileSystemModel], file=0x555557937a00, info=0x555558121c70 [GFileInfo], column=8, value=0x555558233c88, data=0x555557ed2c40)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkfilechooserwidget.c:5161
#16 0x00007ffff73eedc8 in _gtk_file_system_model_get_value (model=model@entry=0x555558054550 [GtkFileSystemModel], iter=<optimized out>, column=column@entry=8)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkfilesystemmodel.c:1750
#17 0x00007ffff73eee9d in gtk_file_system_model_get_value (tree_model=0x555558054550, iter=<optimized out>, column=<optimized out>, value=0x7fffffffab80)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkfilesystemmodel.c:618
#18 0x00007ffff7343e70 in apply_cell_attributes (renderer=0x555557eaf5a0 [GtkCellRendererPixbuf], info=0x5555578ed4c0, data=0x7fffffffac10)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkcellarea.c:1249
#19 0x00007ffff6f93a30 in g_hash_table_foreach (hash_table=0x7ffeb4003240 = {...}, func=func@entry=0x7ffff7343da0 <apply_cell_attributes>, user_data=user_data@entry=0x7fffffffac10)
    at ../glib-2.72.3/glib/ghash.c:2092
#20 0x00007ffff7343d49 in gtk_cell_area_real_apply_attributes (area=<optimized out>, tree_model=0x555558054550, iter=0x555557930ea0, is_expander=<optimized out>, is_expanded=<optimized out>)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkcellarea.c:1286
#21 0x00007ffff73495bb in gtk_cell_area_box_apply_attributes
    (area=<optimized out>, tree_model=tree_model@entry=0x555558054550, iter=iter@entry=0x555557930ea0, is_expander=<optimized out>, is_expanded=<optimized out>)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkcellareabox.c:1310
#22 0x00007ffff75fb1b7 in _gtk_marshal_VOID__OBJECT_BOXED_BOOLEAN_BOOLEANv
    (closure=0x555557e48f20, return_value=<optimized out>, instance=0x555558004960, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x555557e43fa0)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkmarshalers.c:5446
#23 0x00007ffff6f08862 in _g_closure_invoke_va
    (closure=closure@entry=0x555557e48f20, return_value=return_value@entry=0x0, instance=instance@entry=0x555558004960, args=args@entry=0x7fffffffaef0, n_params=4, param_types=0x555557e43fa0)
    at ../glib-2.72.3/gobject/gclosure.c:893
#24 0x00007ffff6f20f53 in g_signal_emit_valist (instance=0x555558004960, signal_id=268, detail=<optimized out>, var_args=var_args@entry=0x7fffffffaef0) at ../glib-2.72.3/gobject/gsignal.c:3406
#25 0x00007ffff6f21157 in g_signal_emit (instance=instance@entry=0x555558004960, signal_id=<optimized out>, detail=detail@entry=0) at ../glib-2.72.3/gobject/gsignal.c:3553
#26 0x00007ffff7345a86 in gtk_cell_area_apply_attributes (area=0x555558004960 [GtkCellAreaBox], tree_model=0x555558054550, iter=iter@entry=0x7fffffffb170, is_expander=0, is_expanded=0)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkcellarea.c:2373
#27 0x00007ffff75971d6 in gtk_tree_view_column_cell_set_cell_data
    (tree_column=tree_column@entry=0x555557ff70d0 [GtkTreeViewColumn], tree_model=<optimized out>, iter=iter@entry=0x7fffffffb170, is_expander=<optimized out>, is_expanded=<optimized out>)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtktreeviewcolumn.c:2821
#28 0x00007ffff757bf17 in validate_row (tree_view=tree_view@entry=0x555557e447e0 [GtkTreeView], tree=0x55555814f4f0, node=0x7ffecc01c660, iter=iter@entry=0x7fffffffb170, path=path@entry=0x555557f6e810)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtktreeview.c:6418
#29 0x00007ffff757f107 in validate_visible_area (tree_view=0x555557e447e0 [GtkTreeView]) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtktreeview.c:6742
#30 do_presize_handler (tree_view=0x555557e447e0 [GtkTreeView]) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtktreeview.c:7102
#31 0x00007ffff7585675 in validate_rows (tree_view=0x555557e447e0 [GtkTreeView]) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtktreeview.c:7145
#32 0x00007ffff7b0ec89 in gdk_threads_dispatch (data=0x5555579321a0) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gdk/gdk.c:769
#33 0x00007ffff6fa59d5 in g_main_dispatch (context=0x5555577e2860) at ../glib-2.72.3/glib/gmain.c:3417
#34 g_main_context_dispatch (context=0x5555577e2860) at ../glib-2.72.3/glib/gmain.c:4135
#35 0x00007ffff6fa5d78 in g_main_context_iterate (context=0x5555577e2860, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib-2.72.3/glib/gmain.c:4211
#36 0x00007ffff6fa6063 in g_main_loop_run (loop=loop@entry=0x5555580df790) at ../glib-2.72.3/glib/gmain.c:4411
#37 0x00007ffff744ef4d in gtk_main () at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkmain.c:1329
#38 0x00005555559afbd5 in wxGUIEventLoop::DoRun() ()
#39 0x0000555555ae102d in wxEventLoopBase::Run() ()
#40 0x00005555558e671e in wxDialog::ShowModal() ()
#41 0x00005555559cb750 in wxFileDialog::ShowModal() ()
#42 0x0000555555ee36d8 in MainWindow::OnFileMenu(wxCommandEvent&) (this=0x555557a4c3b0, event=<optimized out>) at /home/tatsh/dev/overlay/Cemu/src/gui/MainWindow.cpp:617
#43 0x0000555555b8ab76 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
#44 0x0000555555b8ace3 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) ()
#45 0x0000555555b8b0a9 in wxEvtHandler::TryHereOnly(wxEvent&) ()
#46 0x0000555555b8b12b in wxEvtHandler::ProcessEventLocally(wxEvent&) ()
#47 0x0000555555b8b1d1 in wxEvtHandler::ProcessEvent(wxEvent&) ()
#48 0x0000555555971ea1 in wxWindowBase::TryAfter(wxEvent&) ()
#49 0x0000555555b8bb07 in wxEvtHandler::SafelyProcessEvent(wxEvent&) ()
#50 0x000055555592edf6 in wxMenuBase::DoProcessEvent(wxMenuBase*, wxEvent&, wxWindow*) ()
#51 0x000055555592f0ac in wxMenuBase::SendEvent(int, int) ()
(ins)--Type <RET> for more, q to quit, c to continue without paging--
#52 0x00005555558e73f1 in menuitem_activate ()
#56 0x00007ffff6f21157 in <emit signal ??? on instance 0x555557ab23a0 [GtkMenuItem]> (instance=instance@entry=0x555557ab23a0, signal_id=<optimized out>, detail=detail@entry=0)
    at ../glib-2.72.3/gobject/gsignal.c:3553
    #53 0x00007ffff6f08649 in g_closure_invoke
    (closure=0x555557a49610, return_value=return_value@entry=0x0, n_param_values=1, param_values=param_values@entry=0x7fffffffc100, invocation_hint=invocation_hint@entry=0x7fffffffc080)
    at ../glib-2.72.3/gobject/gclosure.c:830
    #54 0x00007ffff6f1a79a in signal_emit_unlocked_R
    (node=node@entry=0x5555578b44f0, detail=detail@entry=0, instance=instance@entry=0x555557ab23a0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffc100)
    at ../glib-2.72.3/gobject/gsignal.c:3743
    #55 0x00007ffff6f20bf9 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffc2b0) at ../glib-2.72.3/gobject/gsignal.c:3496
#57 0x00007ffff75a01b4 in gtk_widget_activate (widget=widget@entry=0x555557ab23a0 [GtkMenuItem]) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkwidget.c:7845
#58 0x00007ffff7463de6 in gtk_menu_shell_activate_item (menu_shell=0x555557ab42b0 [GtkMenu], menu_item=0x555557ab23a0 [GtkMenuItem], force_deactivate=<optimized out>)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkmenushell.c:1375
#59 0x00007ffff74640c3 in gtk_menu_shell_button_release (widget=0x555557ab42b0 [GtkMenu], event=<optimized out>) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkmenushell.c:791
#60 0x00007ffff75f4256 in _gtk_marshal_BOOLEAN__BOXEDv
    (closure=0x5555578aaa40, return_value=0x7fffffffc5b0, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x555557889d20)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkmarshalers.c:129
#61 0x00007ffff6f08862 in _g_closure_invoke_va
    (closure=closure@entry=0x5555578aaa40, return_value=return_value@entry=0x7fffffffc5b0, instance=instance@entry=0x555557ab42b0, args=args@entry=0x7fffffffc680, n_params=1, param_types=0x555557889d20)
    at ../glib-2.72.3/gobject/gclosure.c:893
#62 0x00007ffff6f202f2 in g_signal_emit_valist (instance=0x555557ab42b0, signal_id=84, detail=<optimized out>, var_args=var_args@entry=0x7fffffffc680) at ../glib-2.72.3/gobject/gsignal.c:3406
#63 0x00007ffff6f21157 in g_signal_emit (instance=instance@entry=0x555557ab42b0, signal_id=<optimized out>, detail=detail@entry=0) at ../glib-2.72.3/gobject/gsignal.c:3553
#64 0x00007ffff759d244 in gtk_widget_event_internal (widget=widget@entry=0x555557ab42b0 [GtkMenu], event=event@entry=0x7ffec4003710)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkwidget.c:7812
#65 0x00007ffff759fd72 in gtk_widget_event_internal (event=0x7ffec4003710, widget=0x555557ab42b0 [GtkMenu]) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkwidget.c:7383
#66 0x00007ffff744e330 in propagate_event_up (topmost=<optimized out>, event=<optimized out>, widget=0x555557ab42b0 [GtkMenu]) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkmain.c:2588
#67 propagate_event (widget=widget@entry=0x555557ab23a0 [GtkMenuItem], event=event@entry=0x7ffec4003710, captured=captured@entry=0, topmost=topmost@entry=0x0)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkmain.c:2691
#68 0x00007ffff744f5ef in gtk_propagate_event (widget=widget@entry=0x555557ab23a0 [GtkMenuItem], event=event@entry=0x7ffec4003710) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkmain.c:2725
#69 0x00007ffff744fd7d in gtk_main_do_event (event=0x7ffec4003710) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkmain.c:1921
#70 gtk_main_do_event (event=<optimized out>) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkmain.c:1691
#71 0x00007ffff7b1b435 in _gdk_event_emit (event=event@entry=0x7ffec4003710) at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gdk/gdkevents.c:73
#72 0x00007ffff7b4fb82 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>)
    at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gdk/x11/gdkeventsource.c:367
#73 0x00007ffff6fa5acb in g_main_dispatch (context=0x5555577e2860) at ../glib-2.72.3/glib/gmain.c:3417
#74 g_main_context_dispatch (context=0x5555577e2860) at ../glib-2.72.3/glib/gmain.c:4135
#75 0x00007ffff6fa5d78 in g_main_context_iterate (context=0x5555577e2860, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib-2.72.3/glib/gmain.c:4211
#76 0x00007ffff6fa6063 in g_main_loop_run (loop=loop@entry=0x555557c844a0) at ../glib-2.72.3/glib/gmain.c:4411
#77 0x00007ffff744ef4d in gtk_main () at /var/tmp/portage/x11-libs/gtk+-3.24.34/work/gtk+-3.24.34/gtk/gtkmain.c:1329
#78 0x00005555559afbd5 in wxGUIEventLoop::DoRun() ()
#79 0x0000555555ae102d in wxEventLoopBase::Run() ()
#80 0x0000555555ab64c6 in wxAppConsoleBase::OnRun() ()
#81 0x00005555560b7903 in wxEntry(int&, wchar_t**) ()
#82 0x0000555555f70640 in gui_create() () at /home/tatsh/dev/overlay/Cemu/src/gui/guiWrapper.cpp:42
#83 0x00005555558a5830 in mainEmulatorHLE() () at /home/tatsh/dev/overlay/Cemu/src/main.cpp:320
#84 0x00005555558a5b0a in main(int, char**) (argc=1, argv=0x7fffffffccb8) at /home/tatsh/dev/overlay/Cemu/src/main.cpp:421
```
